-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.12.1.454
-- Module  Version: 5.7
-- Sun Jul 10 10:17:52 2022

-- parameterized module component declaration
component main_clock
    port (CLKI: in  std_logic; CLKOP: out  std_logic);
end component;

-- parameterized module component instance
__ : main_clock
    port map (CLKI=>__, CLKOP=>__);
