/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2023.1.1.200.1
    Soft IP Version: 1.4.0
    2023 10 23 22:30:11
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module main_oscillator (hf_out_en_i, hf_clk_out_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  hf_out_en_i;
    output  hf_clk_out_o;
endmodule